# fly.toml app configuration file generated for fluffy-oil on 2023-10-04T17:50:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fluffy-oil"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 4507
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
