version: 3

tasks:
  cache:
    cmd: deno cache deps.ts 

  dev:
    deps:
      - cache
    cmd: infisical run --env=dev --path=fluffy-oil -- deno task start --watch=stylesheets,fonts

  env:
    cmds:
      - infisical secrets --env=dev --path=fluffy-oil {{.CLI_ARGS}}

  img:
    cmds: 
      - docker build -t fluffy-oil .
      - docker run --rm -p 4507:4507 fluffy-oil
  
  htmx:
    cmds:
      - curl -L -o scripts/htmx.min.js https://unpkg.com/htmx.org@latest/dist/htmx.min.js
      - curl -L -o scripts/hyperscript.min.js https://unpkg.com/hyperscript.org@latest/dist/_hyperscript.min.js

  woff:
    cmds:
      - ./bin/woff2_compress {{.CLI_ARGS}}